### ISSUE TITLE
grappling hook doesnt work

### ISSUE THREAD

**Issue by Dwexy** [Ernest326/PavlovGrapplingHook#1]
whenever i grapple onto something, i just get dragged super slowly across the ground and when i try to jump off a high place, i just end up falling normally.

**Comment by Ernest326** [comment]
Hey, inside the grappling hook custom item, there are settings you can adjust to make the pull stronger if it is too weak

**Comment by Dwexy** [comment]
it seems to be working for everybody else on the grappling hook arena except for me. weird.
